package hamt

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _BucketEntry struct {
	key   _Bytes
	value _Any
}
type BucketEntry = *_BucketEntry

func (n _BucketEntry) FieldKey() Bytes {
	return &n.key
}
func (n _BucketEntry) FieldValue() Any {
	return &n.value
}

type _BucketEntry__Maybe struct {
	m schema.Maybe
	v BucketEntry
}
type MaybeBucketEntry = *_BucketEntry__Maybe

func (m MaybeBucketEntry) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeBucketEntry) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeBucketEntry) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeBucketEntry) AsNode() ipld.Node {
	switch m.m {
	case schema.Maybe_Absent:
		return ipld.Absent
	case schema.Maybe_Null:
		return ipld.Null
	case schema.Maybe_Value:
		return m.v
	default:
		panic("unreachable")
	}
}
func (m MaybeBucketEntry) Must() BucketEntry {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}

var (
	fieldName__BucketEntry_Key   = _String{"key"}
	fieldName__BucketEntry_Value = _String{"value"}
)
var _ ipld.Node = (BucketEntry)(&_BucketEntry{})
var _ schema.TypedNode = (BucketEntry)(&_BucketEntry{})

func (BucketEntry) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Map
}
func (n BucketEntry) LookupByString(key string) (ipld.Node, error) {
	switch key {
	case "key":
		return &n.key, nil
	case "value":
		return &n.value, nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfString(key)}
	}
}
func (n BucketEntry) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ks, err := key.AsString()
	if err != nil {
		return nil, err
	}
	return n.LookupByString(ks)
}
func (BucketEntry) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Map{"hamt.BucketEntry"}.LookupByIndex(0)
}
func (n BucketEntry) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return n.LookupByString(seg.String())
}
func (n BucketEntry) MapIterator() ipld.MapIterator {
	return &_BucketEntry__MapItr{n, 0}
}

type _BucketEntry__MapItr struct {
	n   BucketEntry
	idx int
}

func (itr *_BucketEntry__MapItr) Next() (k ipld.Node, v ipld.Node, _ error) {
	if itr.idx >= 2 {
		return nil, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		k = &fieldName__BucketEntry_Key
		v = &itr.n.key
	case 1:
		k = &fieldName__BucketEntry_Value
		v = &itr.n.value
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_BucketEntry__MapItr) Done() bool {
	return itr.idx >= 2
}

func (BucketEntry) ListIterator() ipld.ListIterator {
	return nil
}
func (BucketEntry) Length() int {
	return 2
}
func (BucketEntry) IsAbsent() bool {
	return false
}
func (BucketEntry) IsNull() bool {
	return false
}
func (BucketEntry) AsBool() (bool, error) {
	return mixins.Map{"hamt.BucketEntry"}.AsBool()
}
func (BucketEntry) AsInt() (int, error) {
	return mixins.Map{"hamt.BucketEntry"}.AsInt()
}
func (BucketEntry) AsFloat() (float64, error) {
	return mixins.Map{"hamt.BucketEntry"}.AsFloat()
}
func (BucketEntry) AsString() (string, error) {
	return mixins.Map{"hamt.BucketEntry"}.AsString()
}
func (BucketEntry) AsBytes() ([]byte, error) {
	return mixins.Map{"hamt.BucketEntry"}.AsBytes()
}
func (BucketEntry) AsLink() (ipld.Link, error) {
	return mixins.Map{"hamt.BucketEntry"}.AsLink()
}
func (BucketEntry) Prototype() ipld.NodePrototype {
	return _BucketEntry__Prototype{}
}

type _BucketEntry__Prototype struct{}

func (_BucketEntry__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _BucketEntry__Builder
	nb.Reset()
	return &nb
}

type _BucketEntry__Builder struct {
	_BucketEntry__Assembler
}

func (nb *_BucketEntry__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_BucketEntry__Builder) Reset() {
	var w _BucketEntry
	var m schema.Maybe
	*nb = _BucketEntry__Builder{_BucketEntry__Assembler{w: &w, m: &m}}
}

type _BucketEntry__Assembler struct {
	w     *_BucketEntry
	m     *schema.Maybe
	state maState
	s     int
	f     int

	cm       schema.Maybe
	ca_key   _Bytes__Assembler
	ca_value _Any__Assembler
}

func (na *_BucketEntry__Assembler) reset() {
	na.state = maState_initial
	na.s = 0
	na.ca_key.reset()
	na.ca_value.reset()
}

var (
	fieldBit__BucketEntry_Key         = 1 << 0
	fieldBit__BucketEntry_Value       = 1 << 1
	fieldBits__BucketEntry_sufficient = 0 + 1<<0 + 1<<1
)

func (na *_BucketEntry__Assembler) BeginMap(int) (ipld.MapAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_BucketEntry{}
	}
	return na, nil
}
func (_BucketEntry__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.MapAssembler{"hamt.BucketEntry"}.BeginList(0)
}
func (na *_BucketEntry__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.MapAssembler{"hamt.BucketEntry"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_BucketEntry__Assembler) AssignBool(bool) error {
	return mixins.MapAssembler{"hamt.BucketEntry"}.AssignBool(false)
}
func (_BucketEntry__Assembler) AssignInt(int) error {
	return mixins.MapAssembler{"hamt.BucketEntry"}.AssignInt(0)
}
func (_BucketEntry__Assembler) AssignFloat(float64) error {
	return mixins.MapAssembler{"hamt.BucketEntry"}.AssignFloat(0)
}
func (_BucketEntry__Assembler) AssignString(string) error {
	return mixins.MapAssembler{"hamt.BucketEntry"}.AssignString("")
}
func (_BucketEntry__Assembler) AssignBytes([]byte) error {
	return mixins.MapAssembler{"hamt.BucketEntry"}.AssignBytes(nil)
}
func (_BucketEntry__Assembler) AssignLink(ipld.Link) error {
	return mixins.MapAssembler{"hamt.BucketEntry"}.AssignLink(nil)
}
func (na *_BucketEntry__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_BucketEntry); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_Map {
		return ipld.ErrWrongKind{TypeName: "hamt.BucketEntry", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustMap, ActualKind: v.ReprKind()}
	}
	itr := v.MapIterator()
	for !itr.Done() {
		k, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleKey().AssignNode(k); err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_BucketEntry__Assembler) Prototype() ipld.NodePrototype {
	return _BucketEntry__Prototype{}
}
func (ma *_BucketEntry__Assembler) valueFinishTidy() bool {
	switch ma.f {
	case 0:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_key.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	case 1:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_value.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (ma *_BucketEntry__Assembler) AssembleEntry(k string) (ipld.NodeAssembler, error) {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleEntry cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleEntry cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleEntry cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleEntry cannot be called on an assembler that's already finished")
	}
	switch k {
	case "key":
		if ma.s&fieldBit__BucketEntry_Key != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__BucketEntry_Key}
		}
		ma.s += fieldBit__BucketEntry_Key
		ma.state = maState_midValue
		ma.f = 0
		ma.ca_key.w = &ma.w.key
		ma.ca_key.m = &ma.cm
		return &ma.ca_key, nil
	case "value":
		if ma.s&fieldBit__BucketEntry_Value != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__BucketEntry_Value}
		}
		ma.s += fieldBit__BucketEntry_Value
		ma.state = maState_midValue
		ma.f = 1
		ma.ca_value.w = &ma.w.value
		ma.ca_value.m = &ma.cm
		return &ma.ca_value, nil
	default:
		return nil, ipld.ErrInvalidKey{TypeName: "hamt.BucketEntry", Key: &_String{k}}
	}
}
func (ma *_BucketEntry__Assembler) AssembleKey() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleKey cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleKey cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleKey cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleKey cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midKey
	return (*_BucketEntry__KeyAssembler)(ma)
}
func (ma *_BucketEntry__Assembler) AssembleValue() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		panic("invalid state: AssembleValue cannot be called when no key is primed")
	case maState_midKey:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		// carry on
	case maState_midValue:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling another value")
	case maState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midValue
	switch ma.f {
	case 0:
		ma.ca_key.w = &ma.w.key
		ma.ca_key.m = &ma.cm
		return &ma.ca_key
	case 1:
		ma.ca_value.w = &ma.w.value
		ma.ca_value.m = &ma.cm
		return &ma.ca_value
	default:
		panic("unreachable")
	}
}
func (ma *_BucketEntry__Assembler) Finish() error {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: Finish cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		panic("invalid state: Finish cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	//FIXME check if all required fields are set
	ma.state = maState_finished
	*ma.m = schema.Maybe_Value
	return nil
}
func (ma *_BucketEntry__Assembler) KeyPrototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (ma *_BucketEntry__Assembler) ValuePrototype(k string) ipld.NodePrototype {
	panic("todo structbuilder mapassembler valueprototype")
}

type _BucketEntry__KeyAssembler _BucketEntry__Assembler

func (_BucketEntry__KeyAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.StringAssembler{"hamt.BucketEntry.KeyAssembler"}.BeginMap(0)
}
func (_BucketEntry__KeyAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.StringAssembler{"hamt.BucketEntry.KeyAssembler"}.BeginList(0)
}
func (na *_BucketEntry__KeyAssembler) AssignNull() error {
	return mixins.StringAssembler{"hamt.BucketEntry.KeyAssembler"}.AssignNull()
}
func (_BucketEntry__KeyAssembler) AssignBool(bool) error {
	return mixins.StringAssembler{"hamt.BucketEntry.KeyAssembler"}.AssignBool(false)
}
func (_BucketEntry__KeyAssembler) AssignInt(int) error {
	return mixins.StringAssembler{"hamt.BucketEntry.KeyAssembler"}.AssignInt(0)
}
func (_BucketEntry__KeyAssembler) AssignFloat(float64) error {
	return mixins.StringAssembler{"hamt.BucketEntry.KeyAssembler"}.AssignFloat(0)
}
func (ka *_BucketEntry__KeyAssembler) AssignString(k string) error {
	if ka.state != maState_midKey {
		panic("misuse: KeyAssembler held beyond its valid lifetime")
	}
	switch k {
	case "key":
		if ka.s&fieldBit__BucketEntry_Key != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__BucketEntry_Key}
		}
		ka.s += fieldBit__BucketEntry_Key
		ka.state = maState_expectValue
		ka.f = 0
	case "value":
		if ka.s&fieldBit__BucketEntry_Value != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__BucketEntry_Value}
		}
		ka.s += fieldBit__BucketEntry_Value
		ka.state = maState_expectValue
		ka.f = 1
	default:
		return ipld.ErrInvalidKey{TypeName: "hamt.BucketEntry", Key: &_String{k}}
	}
	return nil
}
func (_BucketEntry__KeyAssembler) AssignBytes([]byte) error {
	return mixins.StringAssembler{"hamt.BucketEntry.KeyAssembler"}.AssignBytes(nil)
}
func (_BucketEntry__KeyAssembler) AssignLink(ipld.Link) error {
	return mixins.StringAssembler{"hamt.BucketEntry.KeyAssembler"}.AssignLink(nil)
}
func (ka *_BucketEntry__KeyAssembler) AssignNode(v ipld.Node) error {
	if v2, err := v.AsString(); err != nil {
		return err
	} else {
		return ka.AssignString(v2)
	}
}
func (_BucketEntry__KeyAssembler) Prototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (BucketEntry) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n BucketEntry) Representation() ipld.Node {
	return (*_BucketEntry__Repr)(n)
}

type _BucketEntry__Repr _BucketEntry

var _ ipld.Node = &_BucketEntry__Repr{}

func (_BucketEntry__Repr) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_List
}
func (_BucketEntry__Repr) LookupByString(string) (ipld.Node, error) {
	return mixins.List{"hamt.BucketEntry.Repr"}.LookupByString("")
}
func (n *_BucketEntry__Repr) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ki, err := key.AsInt()
	if err != nil {
		return nil, err
	}
	return n.LookupByIndex(ki)
}
func (n *_BucketEntry__Repr) LookupByIndex(idx int) (ipld.Node, error) {
	switch idx {
	case 0:
		return n.key.Representation(), nil
	case 1:
		return n.value.Representation(), nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(idx)}
	}
}
func (n _BucketEntry__Repr) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	i, err := seg.Index()
	if err != nil {
		return nil, ipld.ErrInvalidSegmentForList{TypeName: "hamt.BucketEntry.Repr", TroubleSegment: seg, Reason: err}
	}
	return n.LookupByIndex(i)
}
func (_BucketEntry__Repr) MapIterator() ipld.MapIterator {
	return nil
}
func (n *_BucketEntry__Repr) ListIterator() ipld.ListIterator {
	return &_BucketEntry__ReprListItr{n, 0}
}

type _BucketEntry__ReprListItr struct {
	n   *_BucketEntry__Repr
	idx int
}

func (itr *_BucketEntry__ReprListItr) Next() (idx int, v ipld.Node, err error) {
	if itr.idx >= 2 {
		return -1, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		idx = itr.idx
		v = itr.n.key.Representation()
	case 1:
		idx = itr.idx
		v = itr.n.value.Representation()
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_BucketEntry__ReprListItr) Done() bool {
	return itr.idx >= 2
}

func (rn *_BucketEntry__Repr) Length() int {
	l := 2
	return l
}
func (_BucketEntry__Repr) IsAbsent() bool {
	return false
}
func (_BucketEntry__Repr) IsNull() bool {
	return false
}
func (_BucketEntry__Repr) AsBool() (bool, error) {
	return mixins.List{"hamt.BucketEntry.Repr"}.AsBool()
}
func (_BucketEntry__Repr) AsInt() (int, error) {
	return mixins.List{"hamt.BucketEntry.Repr"}.AsInt()
}
func (_BucketEntry__Repr) AsFloat() (float64, error) {
	return mixins.List{"hamt.BucketEntry.Repr"}.AsFloat()
}
func (_BucketEntry__Repr) AsString() (string, error) {
	return mixins.List{"hamt.BucketEntry.Repr"}.AsString()
}
func (_BucketEntry__Repr) AsBytes() ([]byte, error) {
	return mixins.List{"hamt.BucketEntry.Repr"}.AsBytes()
}
func (_BucketEntry__Repr) AsLink() (ipld.Link, error) {
	return mixins.List{"hamt.BucketEntry.Repr"}.AsLink()
}
func (_BucketEntry__Repr) Prototype() ipld.NodePrototype {
	return _BucketEntry__ReprPrototype{}
}

type _BucketEntry__ReprPrototype struct{}

func (_BucketEntry__ReprPrototype) NewBuilder() ipld.NodeBuilder {
	var nb _BucketEntry__ReprBuilder
	nb.Reset()
	return &nb
}

type _BucketEntry__ReprBuilder struct {
	_BucketEntry__ReprAssembler
}

func (nb *_BucketEntry__ReprBuilder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_BucketEntry__ReprBuilder) Reset() {
	var w _BucketEntry
	var m schema.Maybe
	*nb = _BucketEntry__ReprBuilder{_BucketEntry__ReprAssembler{w: &w, m: &m}}
}

type _BucketEntry__ReprAssembler struct {
	w     *_BucketEntry
	m     *schema.Maybe
	state laState
	f     int

	cm       schema.Maybe
	ca_key   _Bytes__ReprAssembler
	ca_value _Any__ReprAssembler
}

func (na *_BucketEntry__ReprAssembler) reset() {
	na.state = laState_initial
	na.f = 0
	na.ca_key.reset()
	na.ca_value.reset()
}
func (_BucketEntry__ReprAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.ListAssembler{"hamt.BucketEntry.Repr"}.BeginMap(0)
}
func (na *_BucketEntry__ReprAssembler) BeginList(int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_BucketEntry{}
	}
	return na, nil
}
func (na *_BucketEntry__ReprAssembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.ListAssembler{"hamt.BucketEntry.Repr.Repr"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_BucketEntry__ReprAssembler) AssignBool(bool) error {
	return mixins.ListAssembler{"hamt.BucketEntry.Repr"}.AssignBool(false)
}
func (_BucketEntry__ReprAssembler) AssignInt(int) error {
	return mixins.ListAssembler{"hamt.BucketEntry.Repr"}.AssignInt(0)
}
func (_BucketEntry__ReprAssembler) AssignFloat(float64) error {
	return mixins.ListAssembler{"hamt.BucketEntry.Repr"}.AssignFloat(0)
}
func (_BucketEntry__ReprAssembler) AssignString(string) error {
	return mixins.ListAssembler{"hamt.BucketEntry.Repr"}.AssignString("")
}
func (_BucketEntry__ReprAssembler) AssignBytes([]byte) error {
	return mixins.ListAssembler{"hamt.BucketEntry.Repr"}.AssignBytes(nil)
}
func (_BucketEntry__ReprAssembler) AssignLink(ipld.Link) error {
	return mixins.ListAssembler{"hamt.BucketEntry.Repr"}.AssignLink(nil)
}
func (na *_BucketEntry__ReprAssembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_BucketEntry); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_List {
		return ipld.ErrWrongKind{TypeName: "hamt.BucketEntry.Repr", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: v.ReprKind()}
	}
	itr := v.ListIterator()
	for !itr.Done() {
		_, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_BucketEntry__ReprAssembler) Prototype() ipld.NodePrototype {
	return _BucketEntry__ReprPrototype{}
}
func (la *_BucketEntry__ReprAssembler) valueFinishTidy() bool {
	switch la.f {
	case 0:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	case 1:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (la *_BucketEntry__ReprAssembler) AssembleValue() ipld.NodeAssembler {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when still in the middle of assembling the previous value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	if la.f >= 2 {
		return nil // schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(2)} // FIXME: need an error thunking assembler!  it has returned.  sigh.
	}
	la.state = laState_midValue
	switch la.f {
	case 0:
		la.ca_key.w = &la.w.key
		la.ca_key.m = &la.cm
		return &la.ca_key
	case 1:
		la.ca_value.w = &la.w.value
		la.ca_value.m = &la.cm
		return &la.ca_value
	default:
		panic("unreachable")
	}
}
func (la *_BucketEntry__ReprAssembler) Finish() error {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	la.state = laState_finished
	*la.m = schema.Maybe_Value
	return nil
}
func (la *_BucketEntry__ReprAssembler) ValuePrototype(_ int) ipld.NodePrototype {
	panic("todo structbuilder tuplerepr valueprototype")
}
