package hamt

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _Link__HashMapNode struct{ x ipld.Link }
type Link__HashMapNode = *_Link__HashMapNode

func (n Link__HashMapNode) Link() ipld.Link {
	return n.x
}
func (_Link__HashMapNode__Prototype) FromLink(v ipld.Link) (Link__HashMapNode, error) {
	n := _Link__HashMapNode{v}
	return &n, nil
}

type _Link__HashMapNode__Maybe struct {
	m schema.Maybe
	v Link__HashMapNode
}
type MaybeLink__HashMapNode = *_Link__HashMapNode__Maybe

func (m MaybeLink__HashMapNode) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeLink__HashMapNode) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeLink__HashMapNode) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeLink__HashMapNode) AsNode() ipld.Node {
	switch m.m {
	case schema.Maybe_Absent:
		return ipld.Absent
	case schema.Maybe_Null:
		return ipld.Null
	case schema.Maybe_Value:
		return m.v
	default:
		panic("unreachable")
	}
}
func (m MaybeLink__HashMapNode) Must() Link__HashMapNode {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}

var _ ipld.Node = (Link__HashMapNode)(&_Link__HashMapNode{})
var _ schema.TypedNode = (Link__HashMapNode)(&_Link__HashMapNode{})

func (Link__HashMapNode) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Link
}
func (Link__HashMapNode) LookupByString(string) (ipld.Node, error) {
	return mixins.Link{"hamt.Link__HashMapNode"}.LookupByString("")
}
func (Link__HashMapNode) LookupByNode(ipld.Node) (ipld.Node, error) {
	return mixins.Link{"hamt.Link__HashMapNode"}.LookupByNode(nil)
}
func (Link__HashMapNode) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Link{"hamt.Link__HashMapNode"}.LookupByIndex(0)
}
func (Link__HashMapNode) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return mixins.Link{"hamt.Link__HashMapNode"}.LookupBySegment(seg)
}
func (Link__HashMapNode) MapIterator() ipld.MapIterator {
	return nil
}
func (Link__HashMapNode) ListIterator() ipld.ListIterator {
	return nil
}
func (Link__HashMapNode) Length() int {
	return -1
}
func (Link__HashMapNode) IsAbsent() bool {
	return false
}
func (Link__HashMapNode) IsNull() bool {
	return false
}
func (Link__HashMapNode) AsBool() (bool, error) {
	return mixins.Link{"hamt.Link__HashMapNode"}.AsBool()
}
func (Link__HashMapNode) AsInt() (int, error) {
	return mixins.Link{"hamt.Link__HashMapNode"}.AsInt()
}
func (Link__HashMapNode) AsFloat() (float64, error) {
	return mixins.Link{"hamt.Link__HashMapNode"}.AsFloat()
}
func (Link__HashMapNode) AsString() (string, error) {
	return mixins.Link{"hamt.Link__HashMapNode"}.AsString()
}
func (Link__HashMapNode) AsBytes() ([]byte, error) {
	return mixins.Link{"hamt.Link__HashMapNode"}.AsBytes()
}
func (n Link__HashMapNode) AsLink() (ipld.Link, error) {
	return n.x, nil
}
func (Link__HashMapNode) Prototype() ipld.NodePrototype {
	return _Link__HashMapNode__Prototype{}
}

type _Link__HashMapNode__Prototype struct{}

func (_Link__HashMapNode__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _Link__HashMapNode__Builder
	nb.Reset()
	return &nb
}

type _Link__HashMapNode__Builder struct {
	_Link__HashMapNode__Assembler
}

func (nb *_Link__HashMapNode__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_Link__HashMapNode__Builder) Reset() {
	var w _Link__HashMapNode
	var m schema.Maybe
	*nb = _Link__HashMapNode__Builder{_Link__HashMapNode__Assembler{w: &w, m: &m}}
}

type _Link__HashMapNode__Assembler struct {
	w *_Link__HashMapNode
	m *schema.Maybe
}

func (na *_Link__HashMapNode__Assembler) reset() {}
func (_Link__HashMapNode__Assembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.LinkAssembler{"hamt.Link__HashMapNode"}.BeginMap(0)
}
func (_Link__HashMapNode__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.LinkAssembler{"hamt.Link__HashMapNode"}.BeginList(0)
}
func (na *_Link__HashMapNode__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.LinkAssembler{"hamt.Link__HashMapNode"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	}
	panic("unreachable")
}
func (_Link__HashMapNode__Assembler) AssignBool(bool) error {
	return mixins.LinkAssembler{"hamt.Link__HashMapNode"}.AssignBool(false)
}
func (_Link__HashMapNode__Assembler) AssignInt(int) error {
	return mixins.LinkAssembler{"hamt.Link__HashMapNode"}.AssignInt(0)
}
func (_Link__HashMapNode__Assembler) AssignFloat(float64) error {
	return mixins.LinkAssembler{"hamt.Link__HashMapNode"}.AssignFloat(0)
}
func (_Link__HashMapNode__Assembler) AssignString(string) error {
	return mixins.LinkAssembler{"hamt.Link__HashMapNode"}.AssignString("")
}
func (_Link__HashMapNode__Assembler) AssignBytes([]byte) error {
	return mixins.LinkAssembler{"hamt.Link__HashMapNode"}.AssignBytes(nil)
}
func (na *_Link__HashMapNode__Assembler) AssignLink(v ipld.Link) error {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	}
	if na.w == nil {
		na.w = &_Link__HashMapNode{}
	}
	na.w.x = v
	*na.m = schema.Maybe_Value
	return nil
}
func (na *_Link__HashMapNode__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_Link__HashMapNode); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v2, err := v.AsLink(); err != nil {
		return err
	} else {
		return na.AssignLink(v2)
	}
}
func (_Link__HashMapNode__Assembler) Prototype() ipld.NodePrototype {
	return _Link__HashMapNode__Prototype{}
}
func (Link__HashMapNode) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n Link__HashMapNode) Representation() ipld.Node {
	return (*_Link__HashMapNode__Repr)(n)
}

type _Link__HashMapNode__Repr = _Link__HashMapNode

var _ ipld.Node = &_Link__HashMapNode__Repr{}

type _Link__HashMapNode__ReprPrototype = _Link__HashMapNode__Prototype
type _Link__HashMapNode__ReprAssembler = _Link__HashMapNode__Assembler
