package hamt

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _List__Element struct {
	x []_Element
}
type List__Element = *_List__Element
type _List__Element__Maybe struct {
	m schema.Maybe
	v List__Element
}
type MaybeList__Element = *_List__Element__Maybe

func (m MaybeList__Element) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeList__Element) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeList__Element) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeList__Element) AsNode() ipld.Node {
	switch m.m {
	case schema.Maybe_Absent:
		return ipld.Absent
	case schema.Maybe_Null:
		return ipld.Null
	case schema.Maybe_Value:
		return m.v
	default:
		panic("unreachable")
	}
}
func (m MaybeList__Element) Must() List__Element {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}

var _ ipld.Node = (List__Element)(&_List__Element{})
var _ schema.TypedNode = (List__Element)(&_List__Element{})

func (List__Element) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_List
}
func (List__Element) LookupByString(string) (ipld.Node, error) {
	return mixins.List{"hamt.List__Element"}.LookupByString("")
}
func (n List__Element) LookupByNode(k ipld.Node) (ipld.Node, error) {
	idx, err := k.AsInt()
	if err != nil {
		return nil, err
	}
	return n.LookupByIndex(idx)
}
func (n List__Element) LookupByIndex(idx int) (ipld.Node, error) {
	if n.Length() <= idx {
		return nil, ipld.ErrNotExists{ipld.PathSegmentOfInt(idx)}
	}
	v := &n.x[idx]
	return v, nil
}
func (n List__Element) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	i, err := seg.Index()
	if err != nil {
		return nil, ipld.ErrInvalidSegmentForList{TypeName: "hamt.List__Element", TroubleSegment: seg, Reason: err}
	}
	return n.LookupByIndex(i)
}
func (List__Element) MapIterator() ipld.MapIterator {
	return nil
}
func (n List__Element) ListIterator() ipld.ListIterator {
	return &_List__Element__ListItr{n, 0}
}

type _List__Element__ListItr struct {
	n   List__Element
	idx int
}

func (itr *_List__Element__ListItr) Next() (idx int, v ipld.Node, _ error) {
	if itr.idx >= len(itr.n.x) {
		return -1, nil, ipld.ErrIteratorOverread{}
	}
	idx = itr.idx
	x := &itr.n.x[itr.idx]
	v = x
	itr.idx++
	return
}
func (itr *_List__Element__ListItr) Done() bool {
	return itr.idx >= len(itr.n.x)
}

func (n List__Element) Length() int {
	return len(n.x)
}
func (List__Element) IsAbsent() bool {
	return false
}
func (List__Element) IsNull() bool {
	return false
}
func (List__Element) AsBool() (bool, error) {
	return mixins.List{"hamt.List__Element"}.AsBool()
}
func (List__Element) AsInt() (int, error) {
	return mixins.List{"hamt.List__Element"}.AsInt()
}
func (List__Element) AsFloat() (float64, error) {
	return mixins.List{"hamt.List__Element"}.AsFloat()
}
func (List__Element) AsString() (string, error) {
	return mixins.List{"hamt.List__Element"}.AsString()
}
func (List__Element) AsBytes() ([]byte, error) {
	return mixins.List{"hamt.List__Element"}.AsBytes()
}
func (List__Element) AsLink() (ipld.Link, error) {
	return mixins.List{"hamt.List__Element"}.AsLink()
}
func (List__Element) Prototype() ipld.NodePrototype {
	return _List__Element__Prototype{}
}

type _List__Element__Prototype struct{}

func (_List__Element__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _List__Element__Builder
	nb.Reset()
	return &nb
}

type _List__Element__Builder struct {
	_List__Element__Assembler
}

func (nb *_List__Element__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_List__Element__Builder) Reset() {
	var w _List__Element
	var m schema.Maybe
	*nb = _List__Element__Builder{_List__Element__Assembler{w: &w, m: &m}}
}

type _List__Element__Assembler struct {
	w     *_List__Element
	m     *schema.Maybe
	state laState

	cm schema.Maybe
	va _Element__Assembler
}

func (na *_List__Element__Assembler) reset() {
	na.state = laState_initial
	na.va.reset()
}
func (_List__Element__Assembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.ListAssembler{"hamt.List__Element"}.BeginMap(0)
}
func (na *_List__Element__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if sizeHint < 0 {
		sizeHint = 0
	}
	if na.w == nil {
		na.w = &_List__Element{}
	}
	if sizeHint > 0 {
		na.w.x = make([]_Element, 0, sizeHint)
	}
	return na, nil
}
func (na *_List__Element__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.ListAssembler{"hamt.List__Element"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_List__Element__Assembler) AssignBool(bool) error {
	return mixins.ListAssembler{"hamt.List__Element"}.AssignBool(false)
}
func (_List__Element__Assembler) AssignInt(int) error {
	return mixins.ListAssembler{"hamt.List__Element"}.AssignInt(0)
}
func (_List__Element__Assembler) AssignFloat(float64) error {
	return mixins.ListAssembler{"hamt.List__Element"}.AssignFloat(0)
}
func (_List__Element__Assembler) AssignString(string) error {
	return mixins.ListAssembler{"hamt.List__Element"}.AssignString("")
}
func (_List__Element__Assembler) AssignBytes([]byte) error {
	return mixins.ListAssembler{"hamt.List__Element"}.AssignBytes(nil)
}
func (_List__Element__Assembler) AssignLink(ipld.Link) error {
	return mixins.ListAssembler{"hamt.List__Element"}.AssignLink(nil)
}
func (na *_List__Element__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_List__Element); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_List {
		return ipld.ErrWrongKind{TypeName: "hamt.List__Element", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: v.ReprKind()}
	}
	itr := v.ListIterator()
	for !itr.Done() {
		_, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_List__Element__Assembler) Prototype() ipld.NodePrototype {
	return _List__Element__Prototype{}
}
func (la *_List__Element__Assembler) valueFinishTidy() bool {
	switch la.cm {
	case schema.Maybe_Value:
		la.va.w = nil
		la.cm = schema.Maybe_Absent
		la.state = laState_initial
		la.va.reset()
		return true
	default:
		return false
	}
}
func (la *_List__Element__Assembler) AssembleValue() ipld.NodeAssembler {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when still in the middle of assembling the previous value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	la.w.x = append(la.w.x, _Element{})
	la.state = laState_midValue
	row := &la.w.x[len(la.w.x)-1]
	la.va.w = row
	la.va.m = &la.cm
	return &la.va
}
func (la *_List__Element__Assembler) Finish() error {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	la.state = laState_finished
	*la.m = schema.Maybe_Value
	return nil
}
func (la *_List__Element__Assembler) ValuePrototype(_ int) ipld.NodePrototype {
	return _Element__Prototype{}
}
func (List__Element) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n List__Element) Representation() ipld.Node {
	return (*_List__Element__Repr)(n)
}

type _List__Element__Repr _List__Element

var _ ipld.Node = &_List__Element__Repr{}

func (_List__Element__Repr) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_List
}
func (_List__Element__Repr) LookupByString(string) (ipld.Node, error) {
	return mixins.List{"hamt.List__Element.Repr"}.LookupByString("")
}
func (nr *_List__Element__Repr) LookupByNode(k ipld.Node) (ipld.Node, error) {
	v, err := (List__Element)(nr).LookupByNode(k)
	if err != nil || v == ipld.Null {
		return v, err
	}
	return v.(Element).Representation(), nil
}
func (nr *_List__Element__Repr) LookupByIndex(idx int) (ipld.Node, error) {
	v, err := (List__Element)(nr).LookupByIndex(idx)
	if err != nil || v == ipld.Null {
		return v, err
	}
	return v.(Element).Representation(), nil
}
func (n _List__Element__Repr) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	i, err := seg.Index()
	if err != nil {
		return nil, ipld.ErrInvalidSegmentForList{TypeName: "hamt.List__Element.Repr", TroubleSegment: seg, Reason: err}
	}
	return n.LookupByIndex(i)
}
func (_List__Element__Repr) MapIterator() ipld.MapIterator {
	return nil
}
func (nr *_List__Element__Repr) ListIterator() ipld.ListIterator {
	return &_List__Element__ReprListItr{(List__Element)(nr), 0}
}

type _List__Element__ReprListItr _List__Element__ListItr

func (itr *_List__Element__ReprListItr) Next() (idx int, v ipld.Node, err error) {
	idx, v, err = (*_List__Element__ListItr)(itr).Next()
	if err != nil || v == ipld.Null {
		return
	}
	return idx, v.(Element).Representation(), nil
}
func (itr *_List__Element__ReprListItr) Done() bool {
	return (*_List__Element__ListItr)(itr).Done()
}

func (rn *_List__Element__Repr) Length() int {
	return len(rn.x)
}
func (_List__Element__Repr) IsAbsent() bool {
	return false
}
func (_List__Element__Repr) IsNull() bool {
	return false
}
func (_List__Element__Repr) AsBool() (bool, error) {
	return mixins.List{"hamt.List__Element.Repr"}.AsBool()
}
func (_List__Element__Repr) AsInt() (int, error) {
	return mixins.List{"hamt.List__Element.Repr"}.AsInt()
}
func (_List__Element__Repr) AsFloat() (float64, error) {
	return mixins.List{"hamt.List__Element.Repr"}.AsFloat()
}
func (_List__Element__Repr) AsString() (string, error) {
	return mixins.List{"hamt.List__Element.Repr"}.AsString()
}
func (_List__Element__Repr) AsBytes() ([]byte, error) {
	return mixins.List{"hamt.List__Element.Repr"}.AsBytes()
}
func (_List__Element__Repr) AsLink() (ipld.Link, error) {
	return mixins.List{"hamt.List__Element.Repr"}.AsLink()
}
func (_List__Element__Repr) Prototype() ipld.NodePrototype {
	return _List__Element__ReprPrototype{}
}

type _List__Element__ReprPrototype struct{}

func (_List__Element__ReprPrototype) NewBuilder() ipld.NodeBuilder {
	var nb _List__Element__ReprBuilder
	nb.Reset()
	return &nb
}

type _List__Element__ReprBuilder struct {
	_List__Element__ReprAssembler
}

func (nb *_List__Element__ReprBuilder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_List__Element__ReprBuilder) Reset() {
	var w _List__Element
	var m schema.Maybe
	*nb = _List__Element__ReprBuilder{_List__Element__ReprAssembler{w: &w, m: &m}}
}

type _List__Element__ReprAssembler struct {
	w     *_List__Element
	m     *schema.Maybe
	state laState

	cm schema.Maybe
	va _Element__ReprAssembler
}

func (na *_List__Element__ReprAssembler) reset() {
	na.state = laState_initial
	na.va.reset()
}
func (_List__Element__ReprAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.ListAssembler{"hamt.List__Element.Repr"}.BeginMap(0)
}
func (na *_List__Element__ReprAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if sizeHint < 0 {
		sizeHint = 0
	}
	if na.w == nil {
		na.w = &_List__Element{}
	}
	if sizeHint > 0 {
		na.w.x = make([]_Element, 0, sizeHint)
	}
	return na, nil
}
func (na *_List__Element__ReprAssembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.ListAssembler{"hamt.List__Element.Repr.Repr"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_List__Element__ReprAssembler) AssignBool(bool) error {
	return mixins.ListAssembler{"hamt.List__Element.Repr"}.AssignBool(false)
}
func (_List__Element__ReprAssembler) AssignInt(int) error {
	return mixins.ListAssembler{"hamt.List__Element.Repr"}.AssignInt(0)
}
func (_List__Element__ReprAssembler) AssignFloat(float64) error {
	return mixins.ListAssembler{"hamt.List__Element.Repr"}.AssignFloat(0)
}
func (_List__Element__ReprAssembler) AssignString(string) error {
	return mixins.ListAssembler{"hamt.List__Element.Repr"}.AssignString("")
}
func (_List__Element__ReprAssembler) AssignBytes([]byte) error {
	return mixins.ListAssembler{"hamt.List__Element.Repr"}.AssignBytes(nil)
}
func (_List__Element__ReprAssembler) AssignLink(ipld.Link) error {
	return mixins.ListAssembler{"hamt.List__Element.Repr"}.AssignLink(nil)
}
func (na *_List__Element__ReprAssembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_List__Element); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_List {
		return ipld.ErrWrongKind{TypeName: "hamt.List__Element.Repr", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: v.ReprKind()}
	}
	itr := v.ListIterator()
	for !itr.Done() {
		_, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_List__Element__ReprAssembler) Prototype() ipld.NodePrototype {
	return _List__Element__ReprPrototype{}
}
func (la *_List__Element__ReprAssembler) valueFinishTidy() bool {
	switch la.cm {
	case schema.Maybe_Value:
		la.va.w = nil
		la.cm = schema.Maybe_Absent
		la.state = laState_initial
		la.va.reset()
		return true
	default:
		return false
	}
}
func (la *_List__Element__ReprAssembler) AssembleValue() ipld.NodeAssembler {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when still in the middle of assembling the previous value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	la.w.x = append(la.w.x, _Element{})
	la.state = laState_midValue
	row := &la.w.x[len(la.w.x)-1]
	la.va.w = row
	la.va.m = &la.cm
	return &la.va
}
func (la *_List__Element__ReprAssembler) Finish() error {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	la.state = laState_finished
	*la.m = schema.Maybe_Value
	return nil
}
func (la *_List__Element__ReprAssembler) ValuePrototype(_ int) ipld.NodePrototype {
	return _Element__ReprPrototype{}
}
