package hamt

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _Value struct {
	tag uint
	x1  _Bool
	x2  _Int
	x3  _Float
	x4  _String
	x5  _Bytes
	x6  _Map
	x7  _List
	x8  _Link
}
type Value = *_Value

type _Value__iface interface {
	_Value__member()
}

func (_Bool) _Value__member()   {}
func (_Int) _Value__member()    {}
func (_Float) _Value__member()  {}
func (_String) _Value__member() {}
func (_Bytes) _Value__member()  {}
func (_Map) _Value__member()    {}
func (_List) _Value__member()   {}
func (_Link) _Value__member()   {}
func (n _Value) AsInterface() _Value__iface {
	switch n.tag {
	case 1:
		return &n.x1
	case 2:
		return &n.x2
	case 3:
		return &n.x3
	case 4:
		return &n.x4
	case 5:
		return &n.x5
	case 6:
		return &n.x6
	case 7:
		return &n.x7
	case 8:
		return &n.x8
	default:
		panic("invalid union state; how did you create this object?")
	}
}

type _Value__Maybe struct {
	m schema.Maybe
	v Value
}
type MaybeValue = *_Value__Maybe

func (m MaybeValue) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeValue) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeValue) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeValue) AsNode() ipld.Node {
	switch m.m {
	case schema.Maybe_Absent:
		return ipld.Absent
	case schema.Maybe_Null:
		return ipld.Null
	case schema.Maybe_Value:
		return m.v
	default:
		panic("unreachable")
	}
}
func (m MaybeValue) Must() Value {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}

var (
	memberName__Value_Bool   = _String{"Bool"}
	memberName__Value_Int    = _String{"Int"}
	memberName__Value_Float  = _String{"Float"}
	memberName__Value_String = _String{"String"}
	memberName__Value_Bytes  = _String{"Bytes"}
	memberName__Value_Map    = _String{"Map"}
	memberName__Value_List   = _String{"List"}
	memberName__Value_Link   = _String{"Link"}
)
var _ ipld.Node = (Value)(&_Value{})
var _ schema.TypedNode = (Value)(&_Value{})

func (Value) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Map
}
func (n Value) LookupByString(key string) (ipld.Node, error) {
	switch key {
	case "Bool":
		if n.tag != 1 {
			return nil, ipld.ErrNotExists{ipld.PathSegmentOfString(key)}
		}
		return &n.x1, nil
	case "Int":
		if n.tag != 2 {
			return nil, ipld.ErrNotExists{ipld.PathSegmentOfString(key)}
		}
		return &n.x2, nil
	case "Float":
		if n.tag != 3 {
			return nil, ipld.ErrNotExists{ipld.PathSegmentOfString(key)}
		}
		return &n.x3, nil
	case "String":
		if n.tag != 4 {
			return nil, ipld.ErrNotExists{ipld.PathSegmentOfString(key)}
		}
		return &n.x4, nil
	case "Bytes":
		if n.tag != 5 {
			return nil, ipld.ErrNotExists{ipld.PathSegmentOfString(key)}
		}
		return &n.x5, nil
	case "Map":
		if n.tag != 6 {
			return nil, ipld.ErrNotExists{ipld.PathSegmentOfString(key)}
		}
		return &n.x6, nil
	case "List":
		if n.tag != 7 {
			return nil, ipld.ErrNotExists{ipld.PathSegmentOfString(key)}
		}
		return &n.x7, nil
	case "Link":
		if n.tag != 8 {
			return nil, ipld.ErrNotExists{ipld.PathSegmentOfString(key)}
		}
		return &n.x8, nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfString(key)}
	}
}
func (n Value) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ks, err := key.AsString()
	if err != nil {
		return nil, err
	}
	return n.LookupByString(ks)
}
func (Value) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Map{"hamt.Value"}.LookupByIndex(0)
}
func (n Value) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return n.LookupByString(seg.String())
}
func (n Value) MapIterator() ipld.MapIterator {
	return &_Value__MapItr{n, false}
}

type _Value__MapItr struct {
	n    Value
	done bool
}

func (itr *_Value__MapItr) Next() (k ipld.Node, v ipld.Node, _ error) {
	if itr.done {
		return nil, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.n.tag {
	case 1:
		k, v = &memberName__Value_Bool, &itr.n.x1
	case 2:
		k, v = &memberName__Value_Int, &itr.n.x2
	case 3:
		k, v = &memberName__Value_Float, &itr.n.x3
	case 4:
		k, v = &memberName__Value_String, &itr.n.x4
	case 5:
		k, v = &memberName__Value_Bytes, &itr.n.x5
	case 6:
		k, v = &memberName__Value_Map, &itr.n.x6
	case 7:
		k, v = &memberName__Value_List, &itr.n.x7
	case 8:
		k, v = &memberName__Value_Link, &itr.n.x8
	default:
		panic("unreachable")
	}
	itr.done = true
	return
}
func (itr *_Value__MapItr) Done() bool {
	return itr.done
}

func (Value) ListIterator() ipld.ListIterator {
	return nil
}
func (Value) Length() int {
	return 1
}
func (Value) IsAbsent() bool {
	return false
}
func (Value) IsNull() bool {
	return false
}
func (Value) AsBool() (bool, error) {
	return mixins.Map{"hamt.Value"}.AsBool()
}
func (Value) AsInt() (int, error) {
	return mixins.Map{"hamt.Value"}.AsInt()
}
func (Value) AsFloat() (float64, error) {
	return mixins.Map{"hamt.Value"}.AsFloat()
}
func (Value) AsString() (string, error) {
	return mixins.Map{"hamt.Value"}.AsString()
}
func (Value) AsBytes() ([]byte, error) {
	return mixins.Map{"hamt.Value"}.AsBytes()
}
func (Value) AsLink() (ipld.Link, error) {
	return mixins.Map{"hamt.Value"}.AsLink()
}
func (Value) Prototype() ipld.NodePrototype {
	return _Value__Prototype{}
}

type _Value__Prototype struct{}

func (_Value__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _Value__Builder
	nb.Reset()
	return &nb
}

type _Value__Builder struct {
	_Value__Assembler
}

func (nb *_Value__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_Value__Builder) Reset() {
	var w _Value
	var m schema.Maybe
	*nb = _Value__Builder{_Value__Assembler{w: &w, m: &m}}
}

type _Value__Assembler struct {
	w     *_Value
	m     *schema.Maybe
	state maState

	cm  schema.Maybe
	ca1 _Bool__Assembler

	ca2 _Int__Assembler

	ca3 _Float__Assembler

	ca4 _String__Assembler

	ca5 _Bytes__Assembler

	ca6 _Map__Assembler

	ca7 _List__Assembler

	ca8 _Link__Assembler
	ca  uint
}

func (na *_Value__Assembler) reset() {
	na.state = maState_initial
	switch na.ca {
	case 0:
		return
	case 1:
		na.ca1.reset()

	case 2:
		na.ca2.reset()

	case 3:
		na.ca3.reset()

	case 4:
		na.ca4.reset()

	case 5:
		na.ca5.reset()

	case 6:
		na.ca6.reset()

	case 7:
		na.ca7.reset()

	case 8:
		na.ca8.reset()
	default:
		panic("unreachable")
	}
	na.ca = 0
	na.cm = schema.Maybe_Absent
}
func (na *_Value__Assembler) BeginMap(int) (ipld.MapAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_Value{}
	}
	return na, nil
}
func (_Value__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.MapAssembler{"hamt.Value"}.BeginList(0)
}
func (na *_Value__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.MapAssembler{"hamt.Value"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_Value__Assembler) AssignBool(bool) error {
	return mixins.MapAssembler{"hamt.Value"}.AssignBool(false)
}
func (_Value__Assembler) AssignInt(int) error {
	return mixins.MapAssembler{"hamt.Value"}.AssignInt(0)
}
func (_Value__Assembler) AssignFloat(float64) error {
	return mixins.MapAssembler{"hamt.Value"}.AssignFloat(0)
}
func (_Value__Assembler) AssignString(string) error {
	return mixins.MapAssembler{"hamt.Value"}.AssignString("")
}
func (_Value__Assembler) AssignBytes([]byte) error {
	return mixins.MapAssembler{"hamt.Value"}.AssignBytes(nil)
}
func (_Value__Assembler) AssignLink(ipld.Link) error {
	return mixins.MapAssembler{"hamt.Value"}.AssignLink(nil)
}
func (na *_Value__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_Value); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_Map {
		return ipld.ErrWrongKind{TypeName: "hamt.Value", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustMap, ActualKind: v.ReprKind()}
	}
	itr := v.MapIterator()
	for !itr.Done() {
		k, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleKey().AssignNode(k); err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_Value__Assembler) Prototype() ipld.NodePrototype {
	return _Value__Prototype{}
}
func (ma *_Value__Assembler) valueFinishTidy() bool {
	switch ma.cm {
	case schema.Maybe_Value:
		ma.state = maState_initial
		return true
	default:
		return false
	}
}
func (ma *_Value__Assembler) AssembleEntry(k string) (ipld.NodeAssembler, error) {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleEntry cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleEntry cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleEntry cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on for the moment, but we'll still be erroring shortly.
	case maState_finished:
		panic("invalid state: AssembleEntry cannot be called on an assembler that's already finished")
	}
	if ma.ca != 0 {
		return nil, schema.ErrNotUnionStructure{TypeName: "hamt.Value", Detail: "cannot add another entry -- a union can only contain one thing!"}
	}
	switch k {
	case "Bool":
		ma.state = maState_midValue
		ma.ca = 1
		ma.w.tag = 1
		ma.ca1.w = &ma.w.x1
		ma.ca1.m = &ma.cm
		return &ma.ca1, nil
	case "Int":
		ma.state = maState_midValue
		ma.ca = 2
		ma.w.tag = 2
		ma.ca2.w = &ma.w.x2
		ma.ca2.m = &ma.cm
		return &ma.ca2, nil
	case "Float":
		ma.state = maState_midValue
		ma.ca = 3
		ma.w.tag = 3
		ma.ca3.w = &ma.w.x3
		ma.ca3.m = &ma.cm
		return &ma.ca3, nil
	case "String":
		ma.state = maState_midValue
		ma.ca = 4
		ma.w.tag = 4
		ma.ca4.w = &ma.w.x4
		ma.ca4.m = &ma.cm
		return &ma.ca4, nil
	case "Bytes":
		ma.state = maState_midValue
		ma.ca = 5
		ma.w.tag = 5
		ma.ca5.w = &ma.w.x5
		ma.ca5.m = &ma.cm
		return &ma.ca5, nil
	case "Map":
		ma.state = maState_midValue
		ma.ca = 6
		ma.w.tag = 6
		ma.ca6.w = &ma.w.x6
		ma.ca6.m = &ma.cm
		return &ma.ca6, nil
	case "List":
		ma.state = maState_midValue
		ma.ca = 7
		ma.w.tag = 7
		ma.ca7.w = &ma.w.x7
		ma.ca7.m = &ma.cm
		return &ma.ca7, nil
	case "Link":
		ma.state = maState_midValue
		ma.ca = 8
		ma.w.tag = 8
		ma.ca8.w = &ma.w.x8
		ma.ca8.m = &ma.cm
		return &ma.ca8, nil
	default:
		return nil, ipld.ErrInvalidKey{TypeName: "hamt.Value", Key: &_String{k}}
	}
}
func (ma *_Value__Assembler) AssembleKey() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleKey cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleKey cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleKey cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on for the moment, but we'll still be erroring shortly... or rather, the keyassembler will be.
	case maState_finished:
		panic("invalid state: AssembleKey cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midKey
	return (*_Value__KeyAssembler)(ma)
}
func (ma *_Value__Assembler) AssembleValue() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		panic("invalid state: AssembleValue cannot be called when no key is primed")
	case maState_midKey:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		// carry on
	case maState_midValue:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling another value")
	case maState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midValue
	switch ma.ca {
	case 0:
		ma.ca1.w = &ma.w.x1
		ma.ca1.m = &ma.cm
		return &ma.ca1
	case 1:
		ma.ca2.w = &ma.w.x2
		ma.ca2.m = &ma.cm
		return &ma.ca2
	case 2:
		ma.ca3.w = &ma.w.x3
		ma.ca3.m = &ma.cm
		return &ma.ca3
	case 3:
		ma.ca4.w = &ma.w.x4
		ma.ca4.m = &ma.cm
		return &ma.ca4
	case 4:
		ma.ca5.w = &ma.w.x5
		ma.ca5.m = &ma.cm
		return &ma.ca5
	case 5:
		ma.ca6.w = &ma.w.x6
		ma.ca6.m = &ma.cm
		return &ma.ca6
	case 6:
		ma.ca7.w = &ma.w.x7
		ma.ca7.m = &ma.cm
		return &ma.ca7
	case 7:
		ma.ca8.w = &ma.w.x8
		ma.ca8.m = &ma.cm
		return &ma.ca8
	default:
		panic("unreachable")
	}
}
func (ma *_Value__Assembler) Finish() error {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: Finish cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		panic("invalid state: Finish cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	if ma.ca == 0 {
		return schema.ErrNotUnionStructure{TypeName: "hamt.Value", Detail: "a union must have exactly one entry (not none)!"}
	}
	ma.state = maState_finished
	*ma.m = schema.Maybe_Value
	return nil
}
func (ma *_Value__Assembler) KeyPrototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (ma *_Value__Assembler) ValuePrototype(k string) ipld.NodePrototype {
	switch k {
	case "Bool":
		return _Bool__Prototype{}
	case "Int":
		return _Int__Prototype{}
	case "Float":
		return _Float__Prototype{}
	case "String":
		return _String__Prototype{}
	case "Bytes":
		return _Bytes__Prototype{}
	case "Map":
		return _Map__Prototype{}
	case "List":
		return _List__Prototype{}
	case "Link":
		return _Link__Prototype{}
	default:
		return nil
	}
}

type _Value__KeyAssembler _Value__Assembler

func (_Value__KeyAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.StringAssembler{"hamt.Value.KeyAssembler"}.BeginMap(0)
}
func (_Value__KeyAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.StringAssembler{"hamt.Value.KeyAssembler"}.BeginList(0)
}
func (na *_Value__KeyAssembler) AssignNull() error {
	return mixins.StringAssembler{"hamt.Value.KeyAssembler"}.AssignNull()
}
func (_Value__KeyAssembler) AssignBool(bool) error {
	return mixins.StringAssembler{"hamt.Value.KeyAssembler"}.AssignBool(false)
}
func (_Value__KeyAssembler) AssignInt(int) error {
	return mixins.StringAssembler{"hamt.Value.KeyAssembler"}.AssignInt(0)
}
func (_Value__KeyAssembler) AssignFloat(float64) error {
	return mixins.StringAssembler{"hamt.Value.KeyAssembler"}.AssignFloat(0)
}
func (ka *_Value__KeyAssembler) AssignString(k string) error {
	if ka.state != maState_midKey {
		panic("misuse: KeyAssembler held beyond its valid lifetime")
	}
	if ka.ca != 0 {
		return schema.ErrNotUnionStructure{TypeName: "hamt.Value", Detail: "cannot add another entry -- a union can only contain one thing!"}
	}
	switch k {
	case "Bool":
		ka.ca = 1
		ka.w.tag = 1
		ka.state = maState_expectValue
		return nil
	case "Int":
		ka.ca = 2
		ka.w.tag = 2
		ka.state = maState_expectValue
		return nil
	case "Float":
		ka.ca = 3
		ka.w.tag = 3
		ka.state = maState_expectValue
		return nil
	case "String":
		ka.ca = 4
		ka.w.tag = 4
		ka.state = maState_expectValue
		return nil
	case "Bytes":
		ka.ca = 5
		ka.w.tag = 5
		ka.state = maState_expectValue
		return nil
	case "Map":
		ka.ca = 6
		ka.w.tag = 6
		ka.state = maState_expectValue
		return nil
	case "List":
		ka.ca = 7
		ka.w.tag = 7
		ka.state = maState_expectValue
		return nil
	case "Link":
		ka.ca = 8
		ka.w.tag = 8
		ka.state = maState_expectValue
		return nil
	default:
		return ipld.ErrInvalidKey{TypeName: "hamt.Value", Key: &_String{k}} // TODO: error quality: ErrInvalidUnionDiscriminant ?
	}
	return nil
}
func (_Value__KeyAssembler) AssignBytes([]byte) error {
	return mixins.StringAssembler{"hamt.Value.KeyAssembler"}.AssignBytes(nil)
}
func (_Value__KeyAssembler) AssignLink(ipld.Link) error {
	return mixins.StringAssembler{"hamt.Value.KeyAssembler"}.AssignLink(nil)
}
func (ka *_Value__KeyAssembler) AssignNode(v ipld.Node) error {
	if v2, err := v.AsString(); err != nil {
		return err
	} else {
		return ka.AssignString(v2)
	}
}
func (_Value__KeyAssembler) Prototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (Value) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n Value) Representation() ipld.Node {
	return (*_Value__Repr)(n)
}

type _Value__Repr _Value

var _ ipld.Node = &_Value__Repr{}

func (n *_Value__Repr) ReprKind() ipld.ReprKind {
	switch n.tag {
	case 1:
		return ipld.ReprKind_Bool
	case 2:
		return ipld.ReprKind_Int
	case 3:
		return ipld.ReprKind_Float
	case 4:
		return ipld.ReprKind_String
	case 5:
		return ipld.ReprKind_Bytes
	case 6:
		return ipld.ReprKind_Map
	case 7:
		return ipld.ReprKind_List
	case 8:
		return ipld.ReprKind_Link
	default:
		panic("unreachable")
	}
}
func (n *_Value__Repr) LookupByString(key string) (ipld.Node, error) {
	switch n.tag {
	case 6:
		return n.x6.Representation().LookupByString(key)
	default:
		return nil, ipld.ErrWrongKind{TypeName: "hamt.Value.Repr", MethodName: "LookupByString", AppropriateKind: ipld.ReprKindSet_JustMap, ActualKind: n.ReprKind()}
	}
}
func (n *_Value__Repr) LookupByNode(key ipld.Node) (ipld.Node, error) {
	switch n.tag {
	case 6:
		return n.x6.Representation().LookupByNode(key)
	case 7:
		return n.x7.Representation().LookupByNode(key)
	default:
		return nil, ipld.ErrWrongKind{TypeName: "hamt.Value.Repr", MethodName: "LookupByNode", AppropriateKind: ipld.ReprKindSet_Recursive, ActualKind: n.ReprKind()}
	}
}
func (n *_Value__Repr) LookupByIndex(idx int) (ipld.Node, error) {
	switch n.tag {
	case 7:
		return n.x7.Representation().LookupByIndex(idx)
	default:
		return nil, ipld.ErrWrongKind{TypeName: "hamt.Value.Repr", MethodName: "LookupByIndex", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: n.ReprKind()}
	}
}
func (n *_Value__Repr) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	switch n.tag {
	case 6:
		return n.x6.Representation().LookupBySegment(seg)
	case 7:
		return n.x7.Representation().LookupBySegment(seg)
	default:
		return nil, ipld.ErrWrongKind{TypeName: "hamt.Value.Repr", MethodName: "LookupBySegment", AppropriateKind: ipld.ReprKindSet_Recursive, ActualKind: n.ReprKind()}
	}
}
func (n *_Value__Repr) MapIterator() ipld.MapIterator {
	switch n.tag {
	case 6:
		return n.x6.Representation().MapIterator()
	default:
		return nil
	}
}
func (n *_Value__Repr) ListIterator() ipld.ListIterator {
	switch n.tag {
	case 7:
		return n.x7.Representation().ListIterator()
	default:
		return nil
	}
}
func (n *_Value__Repr) Length() int {
	switch n.tag {
	case 6:
		return n.x6.Representation().Length()
	case 7:
		return n.x7.Representation().Length()
	default:
		return -1
	}
}
func (n *_Value__Repr) IsAbsent() bool {
	return false
}
func (n *_Value__Repr) IsNull() bool {
	return false
}
func (n *_Value__Repr) AsBool() (bool, error) {
	switch n.tag {
	case 1:
		return n.x1.Representation().AsBool()
	default:
		return false, ipld.ErrWrongKind{TypeName: "hamt.Value.Repr", MethodName: "AsBool", AppropriateKind: ipld.ReprKindSet_JustBool, ActualKind: n.ReprKind()}
	}
}
func (n *_Value__Repr) AsInt() (int, error) {
	switch n.tag {
	case 2:
		return n.x2.Representation().AsInt()
	default:
		return 0, ipld.ErrWrongKind{TypeName: "hamt.Value.Repr", MethodName: "AsInt", AppropriateKind: ipld.ReprKindSet_JustInt, ActualKind: n.ReprKind()}
	}
}
func (n *_Value__Repr) AsFloat() (float64, error) {
	switch n.tag {
	case 3:
		return n.x3.Representation().AsFloat()
	default:
		return 0, ipld.ErrWrongKind{TypeName: "hamt.Value.Repr", MethodName: "AsFloat", AppropriateKind: ipld.ReprKindSet_JustFloat, ActualKind: n.ReprKind()}
	}
}
func (n *_Value__Repr) AsString() (string, error) {
	switch n.tag {
	case 4:
		return n.x4.Representation().AsString()
	default:
		return "", ipld.ErrWrongKind{TypeName: "hamt.Value.Repr", MethodName: "AsString", AppropriateKind: ipld.ReprKindSet_JustString, ActualKind: n.ReprKind()}
	}
}
func (n *_Value__Repr) AsBytes() ([]byte, error) {
	switch n.tag {
	case 5:
		return n.x5.Representation().AsBytes()
	default:
		return nil, ipld.ErrWrongKind{TypeName: "hamt.Value.Repr", MethodName: "AsBytes", AppropriateKind: ipld.ReprKindSet_JustBytes, ActualKind: n.ReprKind()}
	}
}
func (n *_Value__Repr) AsLink() (ipld.Link, error) {
	switch n.tag {
	case 8:
		return n.x8.Representation().AsLink()
	default:
		return nil, ipld.ErrWrongKind{TypeName: "hamt.Value.Repr", MethodName: "AsLink", AppropriateKind: ipld.ReprKindSet_JustLink, ActualKind: n.ReprKind()}
	}
}
func (_Value__Repr) Prototype() ipld.NodePrototype {
	return _Value__ReprPrototype{}
}

type _Value__ReprPrototype struct{}

func (_Value__ReprPrototype) NewBuilder() ipld.NodeBuilder {
	var nb _Value__ReprBuilder
	nb.Reset()
	return &nb
}

type _Value__ReprBuilder struct {
	_Value__ReprAssembler
}

func (nb *_Value__ReprBuilder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_Value__ReprBuilder) Reset() {
	var w _Value
	var m schema.Maybe
	*nb = _Value__ReprBuilder{_Value__ReprAssembler{w: &w, m: &m}}
}

type _Value__ReprAssembler struct {
	w   *_Value
	m   *schema.Maybe
	ca1 _Bool__ReprAssembler
	ca2 _Int__ReprAssembler
	ca3 _Float__ReprAssembler
	ca4 _String__ReprAssembler
	ca5 _Bytes__ReprAssembler
	ca6 _Map__ReprAssembler
	ca7 _List__ReprAssembler
	ca8 _Link__ReprAssembler
	ca  uint
}

func (na *_Value__ReprAssembler) reset() {
	switch na.ca {
	case 0:
		return
	case 1:
		na.ca1.reset()
	case 2:
		na.ca2.reset()
	case 3:
		na.ca3.reset()
	case 4:
		na.ca4.reset()
	case 5:
		na.ca5.reset()
	case 6:
		na.ca6.reset()
	case 7:
		na.ca7.reset()
	case 8:
		na.ca8.reset()
	default:
		panic("unreachable")
	}
	na.ca = 0
}
func (na *_Value__ReprAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign into assembler that's already working on a larger structure!")
	}
	if na.w == nil {
		na.w = &_Value{}
	}
	na.ca = 6
	na.w.tag = 6
	na.ca6.w = &na.w.x6
	na.ca6.m = na.m
	return na.ca6.BeginMap(sizeHint)
	return nil, schema.ErrNotUnionStructure{TypeName: "hamt.Value.Repr", Detail: "BeginMap called but is not valid for any of the kinds that are valid members of this union"}
}
func (na *_Value__ReprAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign into assembler that's already working on a larger structure!")
	}
	if na.w == nil {
		na.w = &_Value{}
	}
	na.ca = 7
	na.w.tag = 7
	na.ca7.w = &na.w.x7
	na.ca7.m = na.m
	return na.ca7.BeginList(sizeHint)
	return nil, schema.ErrNotUnionStructure{TypeName: "hamt.Value.Repr", Detail: "BeginList called but is not valid for any of the kinds that are valid members of this union"}
}
func (na *_Value__ReprAssembler) AssignNull() error {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign into assembler that's already working on a larger structure!")
	}
	return schema.ErrNotUnionStructure{TypeName: "hamt.Value.Repr", Detail: "AssignNull called but is not valid for any of the kinds that are valid members of this union"}
}
func (na *_Value__ReprAssembler) AssignBool(v bool) error {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign into assembler that's already working on a larger structure!")
	}
	if na.w == nil {
		na.w = &_Value{}
	}
	na.ca = 1
	na.w.tag = 1
	na.ca1.w = &na.w.x1
	na.ca1.m = na.m
	return na.ca1.AssignBool(v)
	return schema.ErrNotUnionStructure{TypeName: "hamt.Value.Repr", Detail: "AssignBool called but is not valid for any of the kinds that are valid members of this union"}
}
func (na *_Value__ReprAssembler) AssignInt(v int) error {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign into assembler that's already working on a larger structure!")
	}
	if na.w == nil {
		na.w = &_Value{}
	}
	na.ca = 2
	na.w.tag = 2
	na.ca2.w = &na.w.x2
	na.ca2.m = na.m
	return na.ca2.AssignInt(v)
	return schema.ErrNotUnionStructure{TypeName: "hamt.Value.Repr", Detail: "AssignInt called but is not valid for any of the kinds that are valid members of this union"}
}
func (na *_Value__ReprAssembler) AssignFloat(v float64) error {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign into assembler that's already working on a larger structure!")
	}
	if na.w == nil {
		na.w = &_Value{}
	}
	na.ca = 3
	na.w.tag = 3
	na.ca3.w = &na.w.x3
	na.ca3.m = na.m
	return na.ca3.AssignFloat(v)
	return schema.ErrNotUnionStructure{TypeName: "hamt.Value.Repr", Detail: "AssignFloat called but is not valid for any of the kinds that are valid members of this union"}
}
func (na *_Value__ReprAssembler) AssignString(v string) error {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign into assembler that's already working on a larger structure!")
	}
	if na.w == nil {
		na.w = &_Value{}
	}
	na.ca = 4
	na.w.tag = 4
	na.ca4.w = &na.w.x4
	na.ca4.m = na.m
	return na.ca4.AssignString(v)
	return schema.ErrNotUnionStructure{TypeName: "hamt.Value.Repr", Detail: "AssignString called but is not valid for any of the kinds that are valid members of this union"}
}
func (na *_Value__ReprAssembler) AssignBytes(v []byte) error {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign into assembler that's already working on a larger structure!")
	}
	if na.w == nil {
		na.w = &_Value{}
	}
	na.ca = 5
	na.w.tag = 5
	na.ca5.w = &na.w.x5
	na.ca5.m = na.m
	return na.ca5.AssignBytes(v)
	return schema.ErrNotUnionStructure{TypeName: "hamt.Value.Repr", Detail: "AssignBytes called but is not valid for any of the kinds that are valid members of this union"}
}
func (na *_Value__ReprAssembler) AssignLink(v ipld.Link) error {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign into assembler that's already working on a larger structure!")
	}
	if na.w == nil {
		na.w = &_Value{}
	}
	na.ca = 8
	na.w.tag = 8
	na.ca8.w = &na.w.x8
	na.ca8.m = na.m
	return na.ca8.AssignLink(v)
	return schema.ErrNotUnionStructure{TypeName: "hamt.Value.Repr", Detail: "AssignLink called but is not valid for any of the kinds that are valid members of this union"}
}
func (na *_Value__ReprAssembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_Value); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	switch v.ReprKind() {
	case ipld.ReprKind_Bool:
		v2, _ := v.AsBool()
		return na.AssignBool(v2)
	case ipld.ReprKind_Int:
		v2, _ := v.AsInt()
		return na.AssignInt(v2)
	case ipld.ReprKind_Float:
		v2, _ := v.AsFloat()
		return na.AssignFloat(v2)
	case ipld.ReprKind_String:
		v2, _ := v.AsString()
		return na.AssignString(v2)
	case ipld.ReprKind_Bytes:
		v2, _ := v.AsBytes()
		return na.AssignBytes(v2)
	case ipld.ReprKind_Map:
		na, err := na.BeginMap(v.Length())
		if err != nil {
			return err
		}
		itr := v.MapIterator()
		for !itr.Done() {
			k, v, err := itr.Next()
			if err != nil {
				return err
			}
			if err := na.AssembleKey().AssignNode(k); err != nil {
				return err
			}
			if err := na.AssembleValue().AssignNode(v); err != nil {
				return err
			}
		}
		return na.Finish()
	case ipld.ReprKind_List:
		na, err := na.BeginList(v.Length())
		if err != nil {
			return err
		}
		itr := v.ListIterator()
		for !itr.Done() {
			_, v, err := itr.Next()
			if err != nil {
				return err
			}
			if err := na.AssembleValue().AssignNode(v); err != nil {
				return err
			}
		}
		return na.Finish()
	case ipld.ReprKind_Link:
		v2, _ := v.AsLink()
		return na.AssignLink(v2)
	default:
		panic("unreachable")
	}
}
func (na *_Value__ReprAssembler) Prototype() ipld.NodePrototype {
	return _Value__ReprPrototype{}
}
